#注意每个配置项的冒号后必须有空格
#注意每个配置项的冒号后必须有空格
#注意每个配置项的冒号后必须有空格

server:
  #服务器端口
  port: 9999

#企业微信信息
enterprise:
  #企业应用ID
  agentId: 1000002
  #企业应用Isecret
  secret: 'KLZ80J0Ru9ZQFFqeHhZRSRiMpIqY4QHiD4hgP8Hoolg'
  #企业ID
  corpId: 'wwcd8ad5db933d09cc'


#天行数据相关
tianApi:
  #天行数据key
  tianApiKey: '752fd6c44de81c0876349f2af5b199f6'
  #星座
  XingZuoVlaue: '双子'
  #目标城市ID(推荐) 城市名
  WeatherVlaue: 110108


#推送目标信息
weixin:
  #推送目标企业微信账号，多个接收者请用|分隔，例如 "user1ID|user2ID"
  userIds: "LiuFengMing|PaNiBuZhiDaoGenNiShuoYiXia"

target:
  #日期格式必须为yyyy-MM-dd
  #生日
  birthday: 1998-02-22
  #农历生日
  rBirthday: 19980126
  #生日类型  true为农历  false为阳历
  birthType: true
  #恋爱日期
  romanticDate: 2022-07-26
